# Generated by Django 2.0 on 2019-07-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(default='未名', max_length=300, verbose_name='作者')),
                ('publisher', models.CharField(max_length=50, verbose_name='出版社')),
                ('pubdate', models.CharField(default='1900-01', max_length=50, verbose_name='出版年')),
                ('jingz', models.CharField(blank=True, max_length=20, null=True, verbose_name='精装')),
                ('price', models.FloatField(verbose_name='定价')),
                ('pages', models.IntegerField(verbose_name='页数')),
                ('isbn', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ISBN')),
                ('intro', models.CharField(max_length=1000, verbose_name='内容简介')),
                ('image', models.ImageField(upload_to='upload/%Y/%m', verbose_name='书籍图片')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='添加日期')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launched', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bookid', models.ForeignKey(db_column='bookid', on_delete=django.db.models.deletion.CASCADE, related_name='gifts_book', to='User.Book')),
            ],
            options={
                'db_table': 'gifts',
            },
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=2000)),
                ('message', models.CharField(max_length=2000)),
                ('times', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pending',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('beans', models.FloatField(default=0, verbose_name='鱼豆')),
                ('send_counter', models.IntegerField(default=0, verbose_name='送出')),
                ('receive_counter', models.IntegerField(default=0, verbose_name='收到')),
                ('head_photo', models.CharField(default='upload/head_photo/timg.gif', max_length=5000, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launched', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bookid', models.ForeignKey(db_column='bookid', on_delete=django.db.models.deletion.CASCADE, related_name='wish_book', to='User.Book')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='wish_user', to='User.User')),
            ],
            options={
                'db_table': 'wish',
            },
        ),
        migrations.AddField(
            model_name='pending',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=8, on_delete=django.db.models.deletion.CASCADE, related_name='Pending', to='User.User'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='gifts_user', to='User.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=8, on_delete=django.db.models.deletion.CASCADE, related_name='book_user', to='User.User'),
        ),
    ]
