# Generated by Django 2.0 on 2019-07-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='bookid',
            field=models.ForeignKey(db_column='bookid', default=44, on_delete=django.db.models.deletion.CASCADE, related_name='pending_book', to='User.Book'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='message',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=8, on_delete=django.db.models.deletion.CASCADE, related_name='pending_user', to='User.User'),
        ),
    ]
