# Generated by Django 2.0 on 2019-07-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190708_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='tuid',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='pending',
            name='phone',
            field=models.CharField(max_length=19),
        ),
    ]
