# Generated by Django 2.0 on 2019-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190708_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='tname',
            field=models.CharField(default='qq', max_length=20),
        ),
        migrations.AlterField(
            model_name='pending',
            name='tuid',
            field=models.CharField(max_length=20),
        ),
    ]
