# Generated by Django 2.0 on 2019-07-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190709_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isdel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='allowlogin',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pending',
            name='bookid',
            field=models.ForeignKey(db_column='bookid', on_delete=django.db.models.deletion.CASCADE, related_name='pending_book', to='User.Book'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='tname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pending',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='pending_user', to='User.User'),
        ),
    ]
