"""empty message

Revision ID: 513486c96839
Revises: d39a1c861171
Create Date: 2019-06-16 18:46:46.757348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513486c96839'
down_revision = 'd39a1c861171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('picture', sa.String(length=600), nullable=True))
    op.add_column('user', sa.Column('regtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'regtime')
    op.drop_column('user', 'picture')
    op.drop_column('user', 'grade')
    # ### end Alembic commands ###
