"""empty message

Revision ID: 6b8685518da2
Revises: 
Create Date: 2019-06-16 15:25:02.783825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b8685518da2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bbs_user', 'allowlogin',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('bbs_user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('bbs_user', 'picture',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bbs_user', 'regip',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('bbs_user', 'udertype',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bbs_user', 'udertype',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('bbs_user', 'regip',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('bbs_user', 'picture',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bbs_user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('bbs_user', 'allowlogin',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    # ### end Alembic commands ###
