"""empty message

Revision ID: 6d3c0682a291
Revises: dd808c6ae73d
Create Date: 2019-06-17 17:53:26.536637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d3c0682a291'
down_revision = 'dd808c6ae73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bbs_details', 'authorid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('bbs_details', 'classid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('bbs_details', 'ishot')
    op.drop_column('bbs_details', 'id')
    op.drop_column('bbs_details', 'isdisplay')
    op.drop_column('bbs_details', 'istop')
    op.drop_column('bbs_details', 'attachment')
    op.drop_column('bbs_details', 'style')
    op.drop_column('bbs_details', 'replycount')
    op.drop_column('bbs_details', 'hits')
    op.drop_column('bbs_details', 'rate')
    op.drop_column('bbs_details', 'isdel')
    op.drop_column('bbs_details', 'addip')
    op.drop_column('bbs_details', 'elite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_details', sa.Column('elite', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.add_column('bbs_details', sa.Column('addip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bbs_details', sa.Column('isdel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bbs_details', sa.Column('rate', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.add_column('bbs_details', sa.Column('hits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bbs_details', sa.Column('replycount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bbs_details', sa.Column('style', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('bbs_details', sa.Column('attachment', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('bbs_details', sa.Column('istop', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.add_column('bbs_details', sa.Column('isdisplay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bbs_details', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('bbs_details', sa.Column('ishot', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.alter_column('bbs_details', 'classid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('bbs_details', 'authorid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
