"""empty message

Revision ID: 816b20a8ad3d
Revises: 6b8685518da2
Create Date: 2019-06-16 17:27:06.819993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816b20a8ad3d'
down_revision = '6b8685518da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
