"""empty message

Revision ID: a292c1c91b58
Revises: 6d3c0682a291
Create Date: 2019-06-18 19:43:13.825833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a292c1c91b58'
down_revision = '6d3c0682a291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_details', sa.Column('hits', sa.Integer(), nullable=True))
    op.add_column('bbs_details', sa.Column('rate', sa.SmallInteger(), nullable=False))
    op.add_column('bbs_details', sa.Column('replycount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bbs_details', 'replycount')
    op.drop_column('bbs_details', 'rate')
    op.drop_column('bbs_details', 'hits')
    # ### end Alembic commands ###
