"""empty message

Revision ID: ae3895b0bba2
Revises: 9283d3a1d206
Create Date: 2019-06-21 10:27:16.040454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3895b0bba2'
down_revision = '9283d3a1d206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('place', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('qq', sa.String(length=13), nullable=True))
    op.add_column('user', sa.Column('sex', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'qq')
    op.drop_column('user', 'place')
    # ### end Alembic commands ###
