"""empty message

Revision ID: d39a1c861171
Revises: 816b20a8ad3d
Create Date: 2019-06-16 17:29:30.902307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39a1c861171'
down_revision = '816b20a8ad3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('udertype', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'udertype')
    # ### end Alembic commands ###
