"""empty message

Revision ID: dd808c6ae73d
Revises: 513486c96839
Create Date: 2019-06-16 18:57:06.860620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd808c6ae73d'
down_revision = '513486c96839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('problem', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['problem'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'problem')
    # ### end Alembic commands ###
